Updated iOptron README
indigo-astronomy/indigo pull request #501
Opened 2023-09-24 06:49 UTC by joeytroy

I updated the iOptron README and also added some screenshots as well. Added information on how to pull the port number from the hand controller and to make sure to use the proper protocol version.

2023-09-24 07:10 UTC, rumengb requested changes

2023-09-24 07:10 UTC, rumengb commented on indigo_drivers/mount_ioptron/README.md
> +* CEM60-EC | Default Port 4030
I do not think the default port should be listed in Driver status section. It should probably be moved in the Comments.

2023-09-24 07:10 UTC, rumengb commented on indigo_drivers/mount_ioptron/README.md
> +![Alt text](ioptronsettings.jpg)
I think screenshots do not add any value as different clients show it differently and they do not show the full path to the property. It is better to descibe it in a single sentence.

2023-09-24 07:10 UTC, rumengb commented on indigo_drivers/mount_ioptron/README.md
> +Use URL in form ieq://host:port to connect to the mount over network. The default port can be found through the hand controller going to Settings < Wi-Fi Options < Wireless Status
It is better to use "->" instead of "<" to show the option path.

2023-09-29 17:06 UTC, joeytroy commented
@rumengb I will clean it up and push again.

2023-09-29 17:06 UTC, closed without merging